# Generated by Django 4.0.5 on 2022-08-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='url',
            new_name='slug',
        ),
    ]
